#!/usr/bin/env python3

import sys
import os

import generation_code
import lexer
import parser

if __name__ == '__main__':
    if len(sys.argv) == 1:
        print('Coral Transpiler.')
        while True:
            try:
                source_from_input = input('> ')
            except (EOFError, KeyboardInterrupt):
                break

            source_code = lexer.Source(source_from_input)
            tokens = lexer.tokenizer(source_code)
            parser.replace_keywords(tokens)
            parser.fix_variable_declaration(tokens)
            code = generation_code.tokens_to_code(tokens)
            print(code)

    elif len(sys.argv) == 2:
        source_code = lexer.lexer.Source(sys.argv[1], is_file=True)
        tokens = lexer.tokenizer(source_code)
        parser.replace_keywords(tokens)
        parser.fix_variable_declaration(tokens)
        parser.fix_code_blocks(tokens)
        code = generation_code.tokens_to_code(tokens)

        filename_without_extension = os.path.splitext(sys.argv[1])[0]
        with open(f'{filename_without_extension}.js', 'w') as file_out:
            file_out.write(code)
